USE [master]
GO

/****** Object:  Database [Examen]    Script Date: 4/13/2022 10:19:16 PM ******/
CREATE DATABASE [Examen]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Examen', FILENAME = N'E:\sqlserver\MSSQL11.MSSQLSERVER2\MSSQL\DATA\Examen.mdf' , SIZE = 134144KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Examen_log', FILENAME = N'E:\sqlserver\MSSQL11.MSSQLSERVER2\MSSQL\DATA\Examen_log.ldf' , SIZE = 13632KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Examen] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Examen].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Examen] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Examen] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Examen] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Examen] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Examen] SET ARITHABORT OFF 
GO

ALTER DATABASE [Examen] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Examen] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Examen] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Examen] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Examen] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Examen] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Examen] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Examen] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Examen] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Examen] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Examen] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Examen] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Examen] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Examen] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Examen] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Examen] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Examen] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Examen] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Examen] SET RECOVERY FULL 
GO

ALTER DATABASE [Examen] SET  MULTI_USER 
GO

ALTER DATABASE [Examen] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Examen] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Examen] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Examen] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Examen] SET  READ_WRITE 
GO

